#!/bin/bash

./pi-install-config
cd /temp/
wget http://tenet.dl.sourceforge.net/project/pinguy-os/ISO_Builder/pinguybuilder_4.3-8_all-beta.deb
sudo dpkg -i pinguybuilder_4.3-8_all-beta.deb
cd
sudo apt-fast install -f -y
sudo sed -i -e 's@user-uid [0-9]*@user-uid 990@' /usr/share/initramfs-tools/scripts/casper-bottom/*adduser
