#!/bin/bash

lokasi_config="/tmp/pi-playground"
webkit_theme="pi-lightdm-theme"

# download and enter config location
dependencies ()
{
	sudo apt-get install git -y
	cd /tmp
	if [ ! -d $lokasi_config ]; then
		git clone https://github.com/alunux/pi-playground.git
	fi
	if [ $? -ne 0 ]; then
		echo "Proses Gagal"
		sudo rm -rf $lokasi_config
		exit 1
	fi
	cd $lokasi_config
	sudo cp pi-apt-lists/libreoffice-ppa-trusty.list /etc/apt/sources.list.d/
	sudo cp pi-apt-lists/sources.list /etc/apt/sources.list
	sudo cp pi-apt-lists/xubuntu-dev-extras-trusty.list /etc/apt/sources.list.d/
	sudo cp pi-apt-lists/xubuntu-dev-xfce-4_12-trusty.list /etc/apt/sources.list.d/
	sudo cp pi-apt-lists/libreoffice-ppa.gpg /etc/apt/trusted.gpg.d/
	sudo cp pi-apt-lists/xubuntu-dev-xfce-4_12.gpg /etc/apt/trusted.gpg.d/
	sudo apt-get update -y
	sudo apt-get install lightdm-webkit-greeter fonts-cantarell fonts-lato -y
	sudo apt-get upgrade -y
	sudo apt-get dist-upgrade -y
}

main_process ()
{
	# install icons
	sudo cp -r pi-elementary-icons/elementary /usr/share/icons/
	sudo chmod 755 -R /usr/share/icons/elementary
	sudo cp -r pi-elementary-icons/elementary-add /usr/share/icons/
	sudo chmod 755 -R /usr/share/icons/elementary-add

	# install gtk themes
	sudo cp -r Pi-Green/ /usr/share/themes
	sudo chmod 755 -R /usr/share/themes/Pi-Green
	sudo cp -r Pi-Grey/ /usr/share/themes
	sudo chmod 755 -R /usr/share/themes/Pi-Grey

	# install lightdm themes
	sudo cp -r pi-lightdm-theme/ /usr/share/lightdm-webkit/themes/
	sudo chmod 755 -R /usr/share/lightdm-webkit/themes/pi-lightdm-theme
	sudo sed -i "s~\(webkit-theme=\).*~\1$webkit_theme~g" /etc/lightdm/lightdm-webkit-greeter.conf
	echo "greeter-session=lightdm-webkit-greeter" | sudo tee -a /etc/lightdm/lightdm.conf.d/10-xubuntu.conf

	# install logos
	sudo cp pi-logos/logo-2.png /usr/share/pixmaps
	sudo chmod 664 /usr/share/pixmaps/logo-2.png
	sudo cp /usr/share/pixmaps/logo-2.png /usr/share/pixmaps/xubuntu-logo-menu.png
	sudo cp /usr/share/pixmaps/logo-2.png /usr/share/pixmaps/xubuntu-logo.png

	# install plymouth themes
	sudo cp -r pi-plymouth-theme/ /lib/plymouth/themes/pi
	sudo chmod 755 -R /lib/plymouth/themes/pi
	echo -e "[Plymouth Theme]" \
					"\nName=pi" \
					"\nDescription=A theme that features a background with a logo." \
					"\nModuleName=script" \
					"\n" \
					"\n[script]" \
					"\nImageDir=/lib/plymouth/themes/pi" \
					"\nScriptFile=/lib/plymouth/themes/pi/pi.script" \
					"\n" | sudo tee /lib/plymouth/themes/default.plymouth
	echo -e "[Plymouth Theme]" \
					"\nName=Pi Text" \
					"\nDescription=Text mode theme based on xubuntu-logo theme" \
					"\nModuleName=ubuntu-text" \
					"\n" \
					"\n[ubuntu-text]" \
					"\ntitle=Pi 15.12" \
					"\nblack=0x000000" \
					"\nwhite=0xffffff" \
					"\nbrown=0x000000" \
					"\nblue=0xffffff" | sudo tee /lib/plymouth/themes/text.plymouth

	# install wallpaper
	sudo cp pi-wallpapers/* /usr/share/backgrounds/
	sudo chmod 664 /usr/share/backgrounds/*

	# install panel bg
	sudo cp pi-panel-bg/* /usr/share/pixmaps
	sudo chmod 664 /usr/share/pixmaps/panel.png /usr/share/pixmaps/panel-bg.png

	# install xdg config
	sudo rm -rf /etc/xdg/*
	rm -rf $HOME/.config/xfce4/
	sudo cp -r pi-xdg/* /etc/xdg/
	sudo chmod 755 -R /etc/xdg/

	# setup config
	sudo cp pi-scripts/pi-theme-script /usr/bin/
	sudo chmod 755 /usr/bin/pi-theme-script	
}

after ()
{
	sudo apt-get autoremove --purge
	sudo update-grub
	pi-theme-script grey
}

dependencies
if [ $? -ne 0 ]; then 
		echo "Proses Gagal"
		exit 1
fi
main_process
after
exit 0
