#!/bin/bash

# all variables are declaced here
lokasi_config="/tmp/pi-playground"
webkit_theme="pi-lightdm-theme"
session="Pi Session"
greeter="lightdm-webkit-greeter"
arch=$(uname -m)

# prepare Pi sources.list
prepare_source ()
{
    # copy ubuntu main sources.list file to /etc/apt/
    sudo cp pi-apt-lists/sources.list /etc/apt/sources.list

    # add additional repos for Pi
    sudo cp pi-apt-lists/elementary-os-ubuntu-daily-xenial.list /etc/apt/sources.list.d/
    sudo cp pi-apt-lists/libreoffice-ubuntu-ppa-xenial.list /etc/apt/sources.list.d/

    # add gpg key for additional repos
    sudo cp pi-apt-lists/gpg/libreoffice_ubuntu_ppa.gpg /etc/apt/trusted.gpg.d/
    sudo cp pi-apt-lists/gpg/elementary-os_ubuntu_daily.gpg /etc/apt/trusted.gpg.d/
}

# download and enter config location
dependencies ()
{
    sudo apt-get update -y
    sudo apt-get install git -y
    cd /tmp
    if [ ! -d $lokasi_config ]; then
        git clone https://github.com/alunux/pi-playground.git --depth 1
    fi
    if [ $? -ne 0 ]; then
        echo "Proses Gagal"
        sudo rm -rf $lokasi_config
        exit 1
    fi
    cd $lokasi_config
    prepare_source
    packages=$(cat package_list)
    packages_rm=$(cat package_remove)
    sudo apt-get update -y
    sudo apt-get install apt-fast -y
    sudo apt-get purge $packages_rm -y
    sudo apt-fast install $packages -y
    if [[ "$arch" == "x86_64" ]]; then
		sudo apt-fast install grub-efi-amd64-signed shim-signed -y
	fi
    sudo apt-fast upgrade -y
    sudo apt-fast dist-upgrade -y
}

main_process ()
{
    # distro identity
    echo -e "\nDISTRIB_ID=Pi" \
            "\nDISTRIB_RELEASE=16.04" \
            "\nDISTRIB_CODENAME=xenial" \
            "\nDISTRIB_DESCRIPTION=\"Pi 16.04\"" | sudo tee /etc/lsb-release
    echo "Pi 16.04 \n \l" | sudo tee /etc/issue
    echo "Pi 16.04" | sudo tee /etc/issue.net
    sudo cp /usr/share/python-apt/templates/Ubuntu.info /usr/share/python-apt/templates/Pi.info
    sudo cp /usr/share/python-apt/templates/Ubuntu.mirrors /usr/share/python-apt/templates/Pi.mirrors

    # install gtk themes
    sudo cp -r Pi-Green/ /usr/share/themes
    sudo chmod 755 -R /usr/share/themes/Pi-Green
    sudo cp -r Pi-Grey/ /usr/share/themes
    sudo chmod 755 -R /usr/share/themes/Pi-Grey

    # install Pi session
    sudo cp /usr/share/xsessions/xubuntu.desktop /usr/share/xsessions/pi.desktop
    sudo sed -i "s~\(Name=\).*~\1$session~g" /usr/share/xsessions/pi.desktop

    # install lightdm themes
    sudo cp -r pi-lightdm-theme/ /usr/share/lightdm-webkit/themes/
    sudo chmod 755 -R /usr/share/lightdm-webkit/themes/pi-lightdm-theme
    sudo sed -i "s~\(webkit-theme=\).*~\1$webkit_theme~g" /etc/lightdm/lightdm-webkit-greeter.conf
    echo -e "[greeter]" \
            "\nbackground=/usr/share/backgrounds/wallgrid.png" \
            "\ntheme-name=Pi-Grey" \
            "\nicon-theme-name=elementary-xfce-darker" \
            "\nfont-name=Lato 10" \
            "\nxft-antialias=true" \
            "\nxft-dpi=96" \
            "\nxft-hintstyle=slight" \
            "\nxft-rgba=rgb" \
            "\nshow-indicators=power;~session;~power;" \
            "\nshow-clock=true" \
            "\nclock-format=%d %b, %H:%M" \
            "\nkeyboard=onboard" | sudo tee /etc/lightdm/lightdm-gtk-greeter.conf
    # there are some bugs in our lightdm-webkit-theme, so we disable it
    # sudo sed -i "s~\(greeter-session=\).*~\1$greeter~g" /etc/lightdm/lightdm.conf
    echo -e "[SeatDefaults]" \
			"greeter-session=lightdm-webkit2-greeter" \
			"user-session=your-session" | sudo tee /etc/lightdm/lightdm.conf

    # install logos
    sudo cp pi-logos/logo-2.png /usr/share/pixmaps
    sudo cp pi-logos/logo-7.png /usr/share/pixmaps
    sudo chmod 664 /usr/share/pixmaps/logo-2.png /usr/share/pixmaps/logo-7.png
    sudo cp /usr/share/pixmaps/logo-2.png /usr/share/pixmaps/xubuntu-logo-menu.png
    sudo cp /usr/share/pixmaps/logo-2.png /usr/share/pixmaps/xubuntu-logo.png

    #plymouth config
    #sudo sed -i 's/"quiet splash"/""/g' /etc/default/grub

    # install wallpaper
    sudo cp pi-wallpapers/* /usr/share/backgrounds/
    sudo chmod 664 /usr/share/backgrounds/*

    # install panel bg
    sudo cp pi-panel-bg/* /usr/share/pixmaps
    sudo chmod 664 /usr/share/pixmaps/panel.png /usr/share/pixmaps/panel-bg.png

    # install xdg config
    sudo rm -rf /etc/xdg/*
    rm -rf $HOME/.config/xfce4/
    sudo cp -r pi-xdg/* /etc/xdg/
    sudo chmod 755 -R /etc/xdg/
    cp pi-xdg/Thunar/uca.xml $HOME/.config/Thunar/uca.xml
    chmod 755 $HOME/.config/Thunar/uca.xml

    # install Pi default apps
    sudo cp pi-scripts/pi-theme-script /usr/bin/
    sudo chmod 755 /usr/bin/pi-theme-script
    sudo mkdir -p /usr/share/pi-apps/pi-theme-changer/
    if [[ "$arch" == "x86_64" ]]; then
    	sudo cp pi-theme-changer/bin/pi-theme-changer64 /usr/share/pi-apps/pi-theme-changer/
    	sudo cp pi-theme-changer/pi-theme-changer64.desktop /usr/share/applications/
    else
        sudo cp pi-theme-changer/bin/pi-theme-changer /usr/share/pi-apps/pi-theme-changer/
        sudo cp pi-theme-changer/pi-theme-changer.desktop /usr/share/applications/
    fi
    sudo cp -r pi-theme-changer/img/ /usr/share/pi-apps/pi-theme-changer/
    sudo chmod 755 -R /usr/share/pi-apps/pi-theme-changer/
}

after ()
{
    sudo apt-get purge apport -y
    sudo apt-get autoremove --purge -y
    sudo rm -rf $lokasi_config
    cd $HOME
    sudo update-grub
    sudo tlp start
    pi-theme-script grey
}

dependencies
if [ $? -ne 0 ]; then
    echo "Proses Gagal"
    exit 1
fi
main_process
after
exit 0
